In [1]:
import pandas as pd
data = pd.read_csv("/content/amazon_cells_labelled (1).txt",delimiter= "\t",header=None)

In [2]:
data.head()

                                                   0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [3]:
data.columns = ['feedback','sentiment']

In [4]:
data.head()

                                            feedback  sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [5]:
    import nltk
    from nltk.corpus import stopwords
    from nltk.tokenize import word_tokenize

    # Download the 'stopwords' and 'punkt' (for word_tokenize) resources if you haven't already
    nltk.download('stopwords')
    nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [6]:
stop_words = set(stopwords.words('english')) # Get English stopwords as a set for efficient lookup

In [7]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [10]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [8]:
def remove_stopwords(text):
    # Tokenize the text into words
    words = word_tokenize(text)
    # Remove stopwords from the token
    filtered_sentence = [w for w in words if not w.lower() in stop_words]
    return ' '.join(filtered_sentence)

In [11]:
data['feedback']= data['feedback'].apply(lambda x: remove_stopwords(x))

In [12]:
data['feedback'][0]

'way plug US unless go converter .'

In [ ]:
data['sentiment'][0]

np.int64(0)

In [13]:
def text_preprocessing(feedback):
  return feedback.lower().replace("[^\w\s]","").replace('\d',"") # lower case, remove punctuation, remove number, remove stopwords

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-1806699043.py:2: SyntaxWarning: invalid escape sequence '\w'
  return feedback.lower().replace("[^\w\s]","").replace('\d',"") # lower case, remove punctuation, remove number, remove stopwords
/tmp/ipython-input-1806699043.py:2: SyntaxWarning: invalid escape sequence '\d'
  return feedback.lower().replace("[^\w\s]","").replace('\d',"") # lower case, remove punctuation, remove number, remove stopwords

In [14]:
data['feedback'] = data['feedback'].apply(lambda x: text_preprocessing(x))

In [ ]:
data['feedback'][0]

'way plug us unless go converter .'

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data['feedback'],data['sentiment'],train_size=0.80,random_state=40 )

In [16]:
X_train.head()

970                   plugged find darn thing worked .
137                        headset works peachy-keen .
82     well packaged , arrived time , works intended .
188                                   waste 13 bucks .
358                         phone gets extremely hot !
Name: feedback, dtype: object

In [ ]:
y_train.head()

970    0
137    1
82     1
188    0
358    0
Name: sentiment, dtype: int64

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1,2),max_df=0.7,min_df=0.10,max_features=50000)
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [18]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 211 stored elements and shape (800, 2)>

In [20]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression().fit(X_train,y_train)

In [21]:
y_test_pred = LR.predict(X_test)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.52      1.00      0.68        95
           1       1.00      0.15      0.26       105

    accuracy                           0.56       200
   macro avg       0.76      0.58      0.47       200
weighted avg       0.77      0.56      0.46       200

In [23]:
feedback = "And the sound quality is great"

In [ ]:
feedback = text_preprocessing(feedback)

In [24]:
feedback = remove_stopwords(feedback)

In [25]:
feedback = vectorizer.transform([feedback])

In [26]:
LR.predict(feedback)

array([1])

In [ ]:
if LR.predict(feedback)[0]==0:
  print("Negative sentiment")
else:
  print("Positive sentiment")

Positive sentiment

In [ ]:
# dump model  into  pickle file
import pickle
pickle.dump(LR,open('model.pkl','wb'))